rf_design/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'rf'

urlpatterns = [
    path('', views.index, name='index'),
    path('model_ext', views.model_ext, name='model_ext'),
    path('coupler_sizing', views.coupler_sizing, name='coupler_sizing'),
    ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

rf_insight/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('techno/', include('techno.urls')),
    path('admin/', admin.site.urls),
    path('rf_design/', include('rf_design.urls')),
    #add django site authentification urls
    path('accounts/', include('django.contrib.auth.urls')),
]

techno/urls.py
from django.urls import path

from . import views

app_name = 'techno'

urlpatterns = [
    path('', views.index, name="index"),
    path('explore', views.ListCompoType.as_view(), name="explore"),
    path('list_compo/<int:pk>', views.ListCompo.as_view(), name="list_compo"),
    path('compo/<int:pk>', views.Compo.as_view(), name="compo"),
    path('compo_create/', views.CompoCreate.as_view(), name="newcompo"),
    path('graph/', views.graph, name='graph'),
         ]

rf_insight/views.py
from django.shortcuts import render

def index(request):
    context = {}
    return render(request, "rf_insight/index.html", context)

rf_insight/templates/rf_insight/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% block title %}<title>RF Insight</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-2">
          {% block sidebar %}
           <ul class="sidebar-nav">
               <li><a href="{% url 'index' %}">Home</a></li>
               <li><a href="{% url 'rf:index' %}">RF Design Helper Web</a></li>
               <ul><li><a href="{% url 'rf:model_ext' %}">Model Extraction</a></li></ul>
               <ul><li><a href="{% url 'rf:coupler_sizing' %}">Coupler Sizing</a></li></ul>
               <li><a href="{% url 'techno:index' %}">SoA Explorer</a></li>
               <ul><li><a href="{% url 'techno:explore' %}">Explore</a></li></ul>
               <ul><li><a href="{% url 'techno:graph' %}">Graph</a></li></ul>
               <li><a href="/admin">Admin</a></li>
               {% if user.is_authenticated %}
                    <li>User: {{user.get_username }}</li>
                    <li><a href="{% url 'logout'%}?next={{request.path}}">Logout</a></li>
               {% else %}
                    <li><a href="{% url 'login'%}?next={{request.path}}">Login</a></li>
               {% endif %}
           </ul>
          {% endblock %}
      </div>
         <div class="col-sm-10 ">
             {% block content %}
             {% endblock %}
         </div>
    </div>
  </div>
</body>
{%block script %}
{% endblock %}
</html>

rf_insight/templates/rf_insight/index.html
{% extends "rf_insight/base_generic.html" %}

{% block content %}
    <h2>Home</h2>
    <h3>Welcome to RF Insight</h3>
{% endblock %}