rf_insight/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('techno/', include('techno.urls')),
    path('admin/', admin.site.urls),
    path('rf_design/', include('rf_design.urls')),
    #add django site authentification urls
    path('accounts/', include('django.contrib.auth.urls')),
]

techno/urls.py
from django.urls import path

from . import views

app_name = 'techno'

urlpatterns = [
    path('', views.index, name="index"),
    path('explore', views.ListCompoType.as_view(), name="explore"),
    path('list_compo/<int:pk>', views.ListCompo.as_view(), name="list_compo"),
    path('compo/<int:pk>', views.Compo.as_view(), name="compo"),
    path('compo_create/', views.CompoCreate.as_view(), name="newcompo"),
    path('graph/', views.graph, name='graph'),
         ]

techno/models.py
from django.db import models
from django.urls import reverse


class Key_Param(models.Model):
    UnitsPool = models.TextChoices('UnitsPool', 'Hz W % dB')
    name_text = models.CharField(max_length=200)
    units = models.CharField(blank=True, choices=UnitsPool.choices, max_length=10)

    def __str__(self):
        return f'{self.name_text} ({self.units})'


class Components_Type(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('techno:list_compo', args=[str(self.id)])


class Provider(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Technos_Type(models.Model):
    name_text = models.CharField(max_length=200)

    def __str__(self):
        return self.name_text


class Techno(models.Model):
    name = models.CharField(max_length=200)
    provider = models.ForeignKey(Provider, on_delete=models.CASCADE, default=1)
    node_length = models.IntegerField(default=0)
    techno_type = models.ForeignKey(Technos_Type, on_delete=models.CASCADE, default=1)

    def __str__(self):
        return self.name


class Component(models.Model):
    doi = models.URLField(max_length=200)
    comp_type = models.ForeignKey(Components_Type, on_delete=models.CASCADE, verbose_name='component type')
    perf_record = models.ManyToManyField(Key_Param, through='Key_Perf')
    techno = models.ForeignKey(Techno, on_delete=models.CASCADE)

    def __str__(self):
        return self.doi.split('/')[-1]

    def get_absolute_url(self):
        return reverse('techno:compo', args=[str(self.id)])


class Key_Perf(models.Model):
    component = models.ForeignKey(Component, on_delete=models.CASCADE, default=1)
    key_param = models.ForeignKey(Key_Param, on_delete=models.CASCADE, default=1)
    value = models.FloatField(default=0)

    def __str__(self):
        if self.key_param.units == '%':
            form = '2.2f'
        else:
            form = '3.2e'
        return f'{self.key_param}: {self.value : {form}}{self.key_param.units}'

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['component', 'key_param'], name='perf_record'),
        ]

techno/forms.py
from django import forms
from django.db.utils import ProgrammingError

from .models import Components_Type, Key_Param, Component, Key_Perf

class GraphFrom(forms.Form):
    try:
        choices = Components_Type.objects.all()
        comptype = forms.ChoiceField(choices=choices.values_list())
        x_axis = forms.ChoiceField()
        x_log_scale = forms.BooleanField(required=False)
        y_axis = forms.ChoiceField()
        y_log_scale = forms.BooleanField(required=False)
    except ProgrammingError:
        pass
    
    def __init__(self, *args, **kwargs):
        self.type_id = kwargs.pop('type_id')
        super().__init__(*args, **kwargs)
        
        choices = Key_Param.objects.all().values_list('pk', 'name_text')
        self.fields['y_axis'] = forms.ChoiceField(choices=choices)
        self.fields['x_axis'] = forms.ChoiceField(choices=choices)

PerfInline = forms.inlineformset_factory(Component, Key_Perf, fields=('key_param', 'value'))

class ComponentForm(forms.ModelForm):
    class Meta:
        model = Component
        exclude = ('perf_record',)

techno/views.py
from django.shortcuts import render
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin

from techno.models import Components_Type, Component, Key_Param, Key_Perf
from .forms import GraphFrom, ComponentForm, PerfInline
from bokeh.plotting import figure
from bokeh.embed import components

def index(request):
    context = {
        "compo_num": Component.objects.all().count(),
        "compo_type_num": Components_Type.objects.all().count(),
        }
    return render(request, "techno/index.html", context)

class ListCompoType(generic.ListView):
    model = Components_Type
    context_object_name = "item_list"
    template_name = "techno/list.html"
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Component Type'
        return context

class ListCompo(generic.ListView):
    model = Component
    context_object_name = "item_list"
    template_name = "techno/list.html"
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = Components_Type.objects.get(id = self.kwargs['pk'])
        return context
    def get_queryset(self, **kwargs):
        return Component.objects.filter(comp_type_id= self.kwargs['pk'])

class Compo(generic.DetailView):
    model = Component
    template_name = 'techno/component_detail.html'
    
    def get_context_data(self, **kwargs):
       context = super().get_context_data(**kwargs)
       context['key_perf'] = Key_Perf.objects.filter(component_id=self.kwargs['pk'])
       return context

class CompoCreate(LoginRequiredMixin, generic.View):
    form_class = ComponentForm
    inline_formset = PerfInline
    template_name = "techno/newcompo.html"
    
    def get(self, request, *args, **kwargs):
        form = self.form_class()
        formset = self.inline_formset(instance=Component())
        return render(request, self.template_name, {'form':form, 'formset':formset})
    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        formset = self.inline_formset(request.POST, instance=Component())
        if form.is_valid() and formset.is_valid():
            entity = form.save(commit=True)
            formset.instance = entity
            formset.save()
        return render(request, self.template_name, {'form':form, 'formset':formset})

def axis_type(axis_name, request):
    try:
        request.POST[axis_name]
        return "log"
    except KeyError:
        return "linear"

def graph(request):
    context = {}
    if request.method == 'POST':
        #form parts
        type_id = request.POST["comptype"]
        x_id = request.POST['x_axis']
        y_id = request.POST['y_axis']
        key_param_q = Key_Param.objects
        x_axis = key_param_q.get(pk=x_id)
        y_axis = key_param_q.get(pk=y_id)
        form = GraphFrom(request.POST, type_id=type_id)
        
        #plotting parts
        comp_type = Components_Type.objects.get(pk=type_id)
        plot = figure(
            title = comp_type.name,
            x_axis_label=f"{x_axis.name_text} ({x_axis.units})",
            y_axis_label=f"{y_axis.name_text} ({y_axis.units})",
            x_axis_type=axis_type('x_log_scale', request),
            y_axis_type=axis_type('y_log_scale', request),
            )
        data_id = Component.objects.filter(comp_type_id=type_id, perf_record=x_id).values_list('pk')
        data_set = Key_Perf.objects.filter(key_param__in=[x_id, y_id])
        x_value, y_value = [], []
        for data in data_id:
            try:
                x = data_set.get(component_id=data, key_param_id=x_id).value
                y = data_set.get(component_id=data, key_param_id=y_id).value
                x_value.append(float(x))
                y_value.append(float(y))
            except (KeyError, Key_Perf.DoesNotExist):
                pass
        plot.circle(x_value, y_value, size=5, color="blue")
        script, div = components(plot)
        context = {
                   'script': script,
                   'div': div
                   }
    else:
        form = GraphFrom(initial={'x_axis':3, 'y_axis':2}, type_id='1')
    context['form'] = form
    return render(request, "techno/graph.html", context)

techno/templates/techno/base_generic.html
{% extends "rf_insight/base_generic.html" %}

techno/templates/techno/component_detail.html
{% extends "techno/base_generic.html" %}

{% block content %}
<h2> Summary of {{component}} </h2>

<ul>
    <li>Component Type: <a href='{% url "techno:list_compo" component.comp_type.pk %}'>{{component.comp_type}}</a></li>
    <li>Technology Name: {{component.techno}}</li>
    <li>Performances:
    <table>
    {% for perf in key_perf.all %}
        <tr><td>{{perf.key_param}}</td><td>{{perf.value}}{{perf.key_param.unit}}</td></tr>
    {% endfor %}
    </table>
    <li><a href="{{component.doi}}"> publication (external link) </a></li>
</ul>
{% endblock %}

techno/templates/techno/graph.html
{% extends "techno/base_generic.html" %}

{%block title%}
<title> Graph Test </title>
{%endblock%}


{% block content %}
<h2> Graphics </h2>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="submit" />
</form>

{{div | safe}}
{% endblock %}

{%block script%}
<script type="text/javascript" src="https://cdn.bokeh.org/bokeh/release/bokeh-2.3.0.min.js"></script>
<script type="text/javascript" src="https://cdn.bokeh.org/bokeh/release/bokeh-widgets-2.3.0.min.js"></script>
<script type="text/javascript" src="https://cdn.bokeh.org/bokeh/release/bokeh-tables-2.3.0.min.js"></script>
<script type="text/javascript" src="https://cdn.bokeh.org/bokeh/release/bokeh-api-2.3.0.min.js"></script>
{{script | safe}}
{% endblock %}

techno/templates/techno/list.html
{% extends "techno/base_generic.html" %}

{% block content %}
{% if title %}
    <h1> List of {{title}} </h1>
{% else %}
    <h1> Missing Title </h1>
{% endif %}
{% if item_list %}
    <ul>
    {% for item in item_list %}
        <li> <a href="{{ item.get_absolute_url }}"> {{ item }} </a></li>
    {% endfor %}
    </ul>
{% else %}
    No item found.
{%endif%}
<a href="{% url 'techno:newcompo' %}">Add new</a>
{% endblock %}

techno/templates/techno/newcompo.html
{% extends "techno/base_generic.html" %}

{% block content %}
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    {{ formset.management_form }}
    <div id="formset-container">
    {% for item_form in formset %}
        <div id="formset-{{ forloop.counter0 }}">
            {{ item_form.id }}
            {{ item_form }}
        </div>
    {% endfor %}
    </div>

    <script type="text/html" id="formset-template">
        <div id="formset-__prefix__">
            {{ formset.empty_form }}
        </div>
    </script>

    <a href="#" id="add-item-button" class="btn btn-info add-item">Add formset</a>
    <input type="submit" value="Save">
</form>
<script>
$(function() {
    $('.add-item').on('click', function(ev) {
        ev.preventDefault();
        var count = $('#formset-form-container').children().length;
        console.log(count);
        var tmplMarkup = $('#formset-template').html();
        var compiledTmpl = tmplMarkup.replace(/__prefix__/g, count);
        $('div#formset-form-container').append(compiledTmpl);

        // update form count
        $('#id_formset_set-TOTAL_FORMS').attr('value', count+1);

        // some animate to scroll to view our new form
        $('html, body').animate({
            scrollTop: $("#add-item-button").position().top-200
        }, 800);
    });
});
</script>
{% endblock %}